name: Deploy to S3

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync to S3
        run: |
          aws s3 sync . s3://cloud-resume-123 \
            --exclude ".git/*" \
            --exclude ".github/*" \
            --exclude "README.md" \
            --exclude "cloudformation/*" \
            --include "index.html" \
            --include "*.css" \
            --include "*.js" \
            --include "assets/**" \
            --include "assets/img/**" \
            --include "assets/img/aws-icons/*" \
            --include "*.png" \
            --include "*.ico" \
            --delete \
            --size-only \
            --cache-control "max-age=86400"

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E2P6K4IJHJ73QU \
            --paths "/*"